
CREATE TABLE IF NOT EXISTS public.australia_healthsites
(
    lat double precision,
    lon double precision,
    osm_id numeric NOT NULL,
    osm_type character varying(250) COLLATE pg_catalog."default",
    completeness numeric,
    meta_operator character varying(250) COLLATE pg_catalog."default",
    meta_health_amenity_type character varying(250) COLLATE pg_catalog."default",
    meta_dispensing character varying(250) COLLATE pg_catalog."default",
    meta_speciality character varying(250) COLLATE pg_catalog."default",
    meta_is_in_health_zone character varying(5) COLLATE pg_catalog."default",
    capacity_staff numeric,
    loc_amenity character varying(250) COLLATE pg_catalog."default",
    changeset_id numeric,
    access_hours character varying(250) COLLATE pg_catalog."default",
    changeset_timestamp character varying(250) COLLATE pg_catalog."default",
    meta_emergency character varying(250) COLLATE pg_catalog."default",
    contact_url character varying(250) COLLATE pg_catalog."default",
    meta_operator_type character varying(250) COLLATE pg_catalog."default",
    meta_id character varying(250) COLLATE pg_catalog."default",
    meta_water_source boolean,
    changeset_version character varying(250) COLLATE pg_catalog."default",
    addr_street character varying(250) COLLATE pg_catalog."default",
    meta_electricity character varying(250) COLLATE pg_catalog."default",
    contact_phone character varying(250) COLLATE pg_catalog."default",
    meta_insurance character varying(100) COLLATE pg_catalog."default",
    status_operational_status character varying(100) COLLATE pg_catalog."default",
    meta_is_in_health_area character varying(10) COLLATE pg_catalog."default",
    addr_postcode character varying(10) COLLATE pg_catalog."default",
    addr_city character varying(250) COLLATE pg_catalog."default",
    meta_wheelchair character varying(50) COLLATE pg_catalog."default",
    capacity_beds numeric,
    changeset_user character varying(100) COLLATE pg_catalog."default",
    "geo+bounds+url" character varying(400) COLLATE pg_catalog."default",
    addr_housenumber character varying(100) COLLATE pg_catalog."default",
    meta_healthcare character varying(100) COLLATE pg_catalog."default",
    loc_name character varying(400) COLLATE pg_catalog."default",
    CONSTRAINT australia_healthsites_pkey PRIMARY KEY (osm_id)
)
